SELECT
    c.CAR_ID,
    c.CAR_TYPE,
    FLOOR(c.DAILY_FEE * 30 * (1 - (p.DISCOUNT_RATE / 100.0))) AS FEE
FROM
    CAR_RENTAL_COMPANY_CAR c
JOIN
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
    ON c.CAR_TYPE = p.CAR_TYPE
WHERE
    c.CAR_TYPE IN ('세단', 'SUV')
    AND p.DURATION_TYPE = '30일 이상'
    AND c.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE NOT (
            END_DATE < '2022-11-01' OR START_DATE > '2022-11-30'
        )
    )
    AND FLOOR(c.DAILY_FEE * 30 * (1 - (p.DISCOUNT_RATE / 100.0))) >= 500000
    AND FLOOR(c.DAILY_FEE * 30 * (1 - (p.DISCOUNT_RATE / 100.0))) < 2000000
ORDER BY
    FEE DESC,
    c.CAR_TYPE ASC,
    c.CAR_ID DESC;
