SELECT c.CAR_ID, c.CAR_TYPE, FLOOR(30*DAILY_FEE*(1-(DISCOUNT_RATE/100))) as FEE
FROM CAR_RENTAL_COMPANY_CAR as c
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as p
ON c.CAR_TYPE = p.CAR_TYPE
WHERE CAR_ID NOT IN (SELECT CAR_ID 
                     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                    WHERE START_DATE<='2022-11-30' and END_DATE>='2022-11-01')
AND p.DURATION_TYPE = '30일 이상'
AND c.CAR_TYPE IN ('세단','SUV')
HAVING FEE >= 500000 and FEE<2000000
ORDER BY FEE desc, c.CAR_TYPE, c.CAR_ID