-- 코드를 입력하세요
SELECT a.APNT_NO,p.PT_NAME,p.PT_NO,a.MCDP_CD,d.DR_NAME,a.APNT_YMD
FROM APPOINTMENT AS a
JOIN PATIENT AS p on p.PT_NO = a.PT_NO
JOIN DOCTOR AS d on d.DR_ID = a.MDDR_ID
WHERE a.APNT_CNCL_YN = 'N' 
AND APNT_YMD BETWEEN '2022-04-13 00:00:00' AND '2022-04-13 23:59:59' 
ORDER BY APNT_YMD