SELECT u.USER_ID, u.NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM USED_GOODS_BOARD AS g
JOIN USED_GOODS_USER AS u ON g.WRITER_ID = u.USER_ID
WHERE g.STATUS = 'DONE'
GROUP BY g.WRITER_ID
HAVING TOTAL_SALES>=700000
ORDER BY TOTAL_SALES
